import React from "react";

export const metadata = {
  title: "About page",
  description: "Generated by create next app",
};

const AboutLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <h2>Layout About</h2>
      <main className="flex justify-center">{children}</main>
    </>
  );
};

export default AboutLayout;
